name: mod_proto_google
description: Public interface definitions of Google APIs for Dart and gRPC.
version: 1.1.0
homepage: https://github.com/cesarmod2017/proto_google/
repository: https://github.com/cesarmod2017/proto_google/


environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  fixnum: ^1.1.1
  protobuf: ^6.0.0

dev_dependencies:
  test: ^1.29.0
  lints: ^6.0.0
